language: java
jdk: openjdk11
notifications:
  email: false
cache:
  directories:
    - $HOME/.m2
before_install: dpkg-query -l google-chrome-stable chromium-browser || true
install: mvn -B -V $MORE_MAVEN_OPTS dependency:resolve compile test-compile
before_script: true
script:
  - mvn -B -V $MORE_MAVEN_OPTS install
  - mvn -B -V $MORE_MAVEN_OPTS javadoc:javadoc
