version: 0.7.ci{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    echo "JAVA_HOME=%JAVA_HOME%"

    set JAVA_HOME=C:\Program Files\Java\jdk1.8.0

    java -version

    mvn --version

    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --version
    
    echo "CHROMEDRIVER_VERSION=%CHROMEDRIVER_VERSION%"

    mvn install --quiet --batch-mode -Dwdm.chromeDriverVersion=%CHROMEDRIVER_VERSION%
